

pod 'AFNetworking', '~> 3.0.0-beta.2'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJRefresh', '~> 3.0.4'
pod 'MJExtension', '~> 3.0.7'

pod 'SVProgressHUD', '~> 2.0.2'

pod 'FMDB'
pod 'WechatShortVideo'
pod 'Masonry'
pod 'BeeCloud'
pod 'DACircularProgress'

